name: Glitch

on:
  push:
    branches:
      - master

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-18.04
    steps:
      - uses: kanadgupta/glitch-sync@master
        with:
          project-id: '${{ secrets.PROJECT_ID }}'
          auth-token: '${{ secrets.AUTH_TOKEN }}'
